### ISSUE TITLE
API key exposed

### ISSUE THREAD

**Issue by afarber** [PacktPublishing/Mastering-iOS-14-Programming-4th-Edition#1]
https://github.com/PacktPublishing/Mastering-iOS-14-Programming-4th-Edition/blob/d0a42e47792565edb8dac7242f94195fa14da4d9/Chapter%209%20-%20Fetching%20from%20Network/URLSession.playground/Pages/02-MovieDb.xcplaygroundpage/Contents.swift#L5

**Comment by shruthis-shetty** [comment]
Please provide more information regarding the issue.

**Comment by marioeguiluz** [comment]
I updated the file! Thanks @afarber
